name: Build, Test and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build --configuration Release --logger trx --results-directory ./TestResults --collect:"XPlat Code Coverage"
          & "$env:USERPROFILE\.dotnet\tools\reportgenerator" -reports:"**/coverage.cobertura.xml" -targetdir:"TestResults/report" -reporttypes:HtmlInline_AzurePipelines

      # - name: Upload test report to GitHub artifacts
      #   uses: actions/upload-artifact@c6cfa433f8162c276b9d85c6d92c9dc7831f6ef8
      #   with:
      #     name: test-report
      #     path: TestResults/report

      # - name: Upload test report to FTP server
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./TestResults/report/
      #     server-dir: /report/

      # - name: Publish IDP API
      #   run: dotnet publish ./SocialSecurity.IDP/SocialSecurity.IDP.csproj -c Release -o ./publish-idp

      # - name: Upload IDP API to FTP server
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./publish-idp/
      #     server-dir: /idp/

      - name: Send test report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ".NET Test Report - CI Pipeline"
          to: protester789@gmail.com
          from: dotnet-pipeline@example.com
          content_type: text/html
          body: |
            <p>Hello Tester,</p>
            <p>Please find the attached test report generated during the latest deployment.</p>
            <p>Report Summary is attached.</p>
            <p>Regards,<br/>GitHub CI/CD</p>
          attachments: TestResults/report/index.html
